export const FETCH_PLANETS = "FETCH_PLANETS";
export const SELECT_PLANETS = "SELECT_PLANETS";
export const SELECTED_VEHICLES = "SELECTED_VEHICLES";
export const FETCH_VEHICLES = "FETCH_VEHICLES";
export const SELECT_VEHICLES = "SELECT_VEHICLES";
export const UPDATE_TIME = "UPDATE_TIME";
export const GET_TIME = "GET_TIME";
export const GET_FINAL = "GET_FINAL";
